version: 2
services:
  - type: web
    name: yolo-detection-server
    env: node
    plan: free
    buildCommand: |
      npm install
      pip install -r requirements.txt
      mkdir -p test_img results/predict results/logs results/labels uploads
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
