name: Deploy Server
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        npm install
        pip install -r requirements.txt
        
    - name: Create directories
      run: |
        mkdir -p test_img results/predict results/logs results/labels uploads
        
    - name: Test server locally
      run: |
        node server.js &
        sleep 5
        curl http://localhost:3000
        
    # Deploy to Render/Railway (example)
    - name: Deploy to Render
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Deploying to production..."
        # Add your deployment commands here
